/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("info.picocli:picocli:4.7.1")
    api("ca.uhn.hapi.fhir:org.hl7.fhir.r4:5.6.971")
    api("ca.uhn.hapi.fhir:org.hl7.fhir.utilities:5.6.971")
    api("ca.uhn.hapi.fhir:hapi-fhir-structures-r4:6.4.3")
    api("ca.uhn.hapi.fhir:hapi-fhir-caching-caffeine:6.6.2")
    api("org.apache.commons:commons-compress:1.22")
    api("com.google.code.gson:gson:2.10.1")
    api("ca.uhn.hapi.fhir:hapi-fhir-utilities:3.8.0")
    api("org.jetbrains.kotlin:kotlin-stdlib:1.8.20-RC")
    api("org.json:json:20230227")
    api("com.thoughtworks.xstream:xstream:1.4.20")
    api("info.cqframework:model:2.6.0")
    api("info.cqframework:elm:2.6.0")
    api("info.cqframework:cql-to-elm:2.6.0")
    api("info.cqframework:elm-jackson:2.6.0")
    api("info.cqframework:model-jackson:2.6.0")
    api("com.fasterxml.jackson.core:jackson-databind:2.14.2")
    api("org.opencds.cqf.cql:engine:2.4.0")
    api("org.opencds.cqf.cql:engine.jackson:2.4.0")
    api("org.opencds.cqf.cql:evaluator:2.6.0")
    api("org.opencds.cqf.cql:evaluator.builder:2.6.0")
    api("org.opencds.cqf.cql:evaluator.dagger:2.6.0")
    api("org.opencds.cqf.cql:evaluator.plandefinition:2.6.0")
    api("com.fasterxml.jackson.core:jackson-annotations:2.14.2")
    api("com.fasterxml.jackson.core:jackson-core:2.14.2")
}

group = "org.smartregister"
version = "2.2.0"
description = "fhircore-tooling"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
