/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "fhircore-tooling"

dependencyResolutionManagement {
  versionCatalogs { create("deps") { from(files("libs.versions.toml")) } }
}
