name: Snapshot Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-SNAPSHOT
      - v[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+-SNAPSHOT
      - v[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+-[0-9a-zA-Z]+-SNAPSHOT

env:
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name:  Run Unit Tests
        run: ./gradlew test
        working-directory: efsity-cli

      - name: Generate & upload library snapshot artifact AAR (Android Archive) file
        run: ./gradlew clean publishMavenPublicationToSonatypeRepository --stacktrace -PSonatypeUsername=${{ secrets.NEXUS_USERNAME }} -PSonatypePassword=${{ secrets.NEXUS_PASSWORD }}
        working-directory: efsity-cli

      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
